name: cd-portfolio

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install front dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Deploy via SFTP (move dist contents to public)
      uses: appleboy/scp-action@v0.1.5
      with:
        debug: true
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "dist/*"  # Nous envoyons uniquement les fichiers dans dist/
        target: "/var/www/portfolio/public/"  # Le dossier cible où les fichiers doivent aller

    # Optional: Supprimer le dossier dist après avoir déployé
    - name: Clean up dist folder on server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          # Vérifier si le dossier dist existe avant de le supprimer
          if [ -d "/var/www/portfolio/public/dist" ]; then
            sudo rm -rf /var/www/portfolio/public/dist/  # Supprimer le dossier dist s'il existe
          else
            echo "Le dossier dist n'existe pas, rien à supprimer."
          fi
