# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

#  lint:
#    name: lint
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      security-events: write
#      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
#    steps:
#      # Checkout action must run prior to eslint check
#    - name: Checkout
#      uses: actions/checkout@v1
#    - name: Lint
#      uses: Krizzu/eslint-check-action@v1.1.0
#      with:
#        ghToken: ${{ secrets.GITHUB_TOKEN }}
#        eslintFiles: "lib, scripts"
#        eslintConfig: "myConfigs/eslint.config.js"
#        eslintExt: "ts, tsx"
  commit-me:
    name: Conventional Commits Compliance
    runs-on: ubuntu-latest
    env:
      # Enable colored output in GitHub Actions
      FORCE_COLOR: 3
    steps:
      - uses: dev-build-deploy/commit-me@v0
        with:
          token: ${{ github.token }}  # Required to retrieve the commits associated with your Pull Request
          include-commits: true  # OPTIONAL; forces the inclusion of commits associated with your Pull Request
